### PR TITLE
elixir implementation disqus sso js config

### PR DESCRIPTION
**Pull request by alexfilatov**

### CODE REVIEW

**Comment by alexfilatov** [comment]
@ryanvalentin any chance to get this merged? :)

**Comment by hlgott1593** [comment]
@alexfilatov Verified with the latest version of Poison `{:poison, "~> 3.1"}` works with your changes. If you don't mind updating the version description, I would be happy to merge in these changes.

**Comment by alexfilatov** [comment]
@hlgott1593 replaced Poison with Jason as it is better now (omg, 4 years ago!) :)

**Comment by hlgott1593** [comment]
@alexfilatov Just tested with Jason, looks good to me. Thanks for the contribution, sorry for the delay :)

**Pull request merged**
